### PR TITLE
Replace background and font

### LINKED ISSUE #15: Replace huge background image
The current background image is several MBytes large. We should reduce the size of it

### PR DESCRIPTION
**Pull request by PhilippJust**
Closes #15

### CODE REVIEW

**Review by pixelbaker — APPROVED** [review]
I like the font much more!
The background is not my cup of tea, but that's personal taste.

**Comment by PhilippJust** [comment]
> I like the font much more!
> The background is not my cup of tea, but that's personal taste.

Do you have another proposal for the background? I think we should make it look appealing for a majority of people :)

**Comment by pixelbaker** [comment]
Can you bring the logo in first and then I try some color combinations and propose another color combination to you. Deal?

**Comment by PhilippJust** [comment]
> Can you bring the logo in first and then I try some color combinations and propose another color combination to you. Deal?

Sounds good to me!

**Pull request merged**
