### PR TITLE
Put in some yellow

### PR DESCRIPTION
**Pull request by pixelbaker**
I believe that look suits our Wilhelm brand more. What do you think?

### CODE REVIEW

**Comment by PhilippJust** [comment]
I find the yellow somehow aggressive/annoying for my eyes if you know what I mean.
On the other hand, darker shades of yellow always look a little dirty.

Maybe we could have a "patterned yellow" like [these yellow wallpapers](https://www.google.com/search?q=yellow+background)

**Comment by pixelbaker** [comment]
Thanks for the Input. Lets have the discussion here: https://trello.com/c/NfYsTZ4g

Can you add your comment there again please?

**Comment by pixelbaker** [comment]
HI @PhilippJust. I changed the color to a light grey as Julia suggested.
But I am having failing tests (html5-validation). Can you help me to figure out whats causing the problem.

**Comment by PhilippJust** [comment]
@pixelbaker It were only some conflict markers in the css file

**Review by PhilippJust — APPROVED** [review]
It looks very oldschool on a large screen without the half-transparent wrapper around the inputs.
But well, that's personal taste :)

**Comment by pixelbaker** [comment]
We are rarely using it on a large screen. The main device are handhelds I believe.
So we should be fine and we can still refine it in the future for other device types.

**Comment by pixelbaker** [comment]
Ahh, sorry, I did that by accident. Is the linter somehow telling me where the error lies. I couldn’t make it out.

**Pull request merged**
