### PR TITLE
Fix/safari compatibility

### PR DESCRIPTION
**Pull request by PhilippJust**
I'll deploy to /preview in order to make it testable for you, @pixelbaker

### CODE REVIEW

**Comment by pixelbaker** [comment]
Have you deployed yet? Right now I am getting: image

**Comment by PhilippJust** [comment]
> Have you deployed yet?

Yes, I have (to .../preview)
Doesn't look like it has changed a thing :(

Can you please paste your console output here again?

**Comment by pixelbaker** [comment]
I pasted it into the Trello Card.

**Comment by PhilippJust** [comment]
:facepalm: 
I pushed the wrong branch to preview...
Please check again :roll_eyes:

**Comment by pixelbaker** [comment]
Yes!!! Works!!

**Comment by PhilippJust** [comment]
I changed the footer styling hoping that safari will stop putting it above the other elements :)
This time I think I deployed the right thing to /preview :)

**Comment by pixelbaker** [comment]
We are getting there. But not yetimage

**Comment by pixelbaker** [comment]
Previously it looked like that: image

**Comment by PhilippJust** [comment]
Aaaaand there's another version deployed to /preview :)

**Comment by pixelbaker** [comment]
Ohh yeah baby, you did it!!

image

**Review by pixelbaker — APPROVED** [review]

**Pull request merged**
