### PR TITLE
Test/add bdd framework

### PR DESCRIPTION
**Pull request by PhilippJust**
This is a very basic draft of how I imagine we could integrate behaviour driven development. I want to start with actual work on the page only after Antonia is back.

### CODE REVIEW

**Comment by PhilippJust** [comment]
@pixelbaker Just a friendly reminder to have a look and leave some feedback :)

**Review by pixelbaker — APPROVED** [review]
That looks fantastic! GO for it tiger! 😉

**Review by pixelbaker — APPROVED** [review]
Test

**Comment by pixelbaker** [comment]
Screenshot 2020-02-13 at 19 58 16
I guess i need to become a reviewer!

**Comment by PhilippJust** [comment]
> 
> 
> Screenshot 2020-02-13 at 19 58 16
> I guess i need to become a reviewer!

Fixed :)

**Pull request merged**
