### PR TITLE
Style

### PR DESCRIPTION
**Pull request by mailantonia**
We made the form look less ugly : )
The background image is to be replaced with an image of Wilhelmsruh.
Feedback is appreciated.

### CODE REVIEW

**Comment by pixelbaker** [comment]
I gonna review it this weekend

**Review by pixelbaker — APPROVED** [review]
Looks much better indeed.
Here is how things look on my Chrome Browser:
Screenshot 2020-03-31 at 16 04 49

I went into compatibility mode for Smartphones and selected iPhone X. The current form is not using the space adequately and the combo boxes look odd. I am not sure if Safari/Chrome on my iPhone would really render the form like on the screenshot, but if it does, then we are missing our target devices. Please keep this in mind in future styling attempts. Maybe try smoke testing a bit more on a smart phone. Feel free to also upload to the webspace I put aside for you.
Screenshot 2020-03-31 at 16 04 12

**Comment by pixelbaker** [comment]
Sorry for not doing the review on the weekend 😔

**Comment by pixelbaker** [comment]
I leave the merging to you @mailantonia

**Comment by PhilippJust** [comment]
@pixelbaker Are you experienced with the browser's simulation of smartphones?
Here is what we got for Iphone X
image

**Comment by pixelbaker** [comment]
Nope, no experience at all. If what your screenshot shows is the real thing later on, we are all good.

**Pull request merged**
